(
~twelve_tone_series = ( // score start
	'': ( // part start
		1: ( // bar 1 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [64.0], pitch: ['e4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [63.0], pitch: ['ds4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [65.0], pitch: ['f4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		2: ( // bar 2 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [80.0], pitch: ['gs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [79.0], pitch: ['g5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [82.0], pitch: ['as5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [81.0], pitch: ['a5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		3: ( // bar 3 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [65.0], pitch: ['f4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [64.0], pitch: ['e4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		4: ( // bar 4 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		5: ( // bar 5 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [81.0], pitch: ['a5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [80.0], pitch: ['gs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [83.0], pitch: ['b5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [82.0], pitch: ['as5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [79.0], pitch: ['g5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		6: ( // bar 6 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [79.0], pitch: ['g5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		7: ( // bar 7 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		8: ( // bar 8 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [79.0], pitch: ['g5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [81.0], pitch: ['a5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [80.0], pitch: ['gs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		9: ( // bar 9 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [62.0], pitch: ['d4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [61.0], pitch: ['cs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [65.0], pitch: ['f4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [63.0], pitch: ['ds4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [64.0], pitch: ['e4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		10: ( // bar 10 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [63.0], pitch: ['ds4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [62.0], pitch: ['d4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [64.0], pitch: ['e4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [65.0], pitch: ['f4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		11: ( // bar 11 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [78.0], pitch: ['fs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [77.0], pitch: ['f5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [80.0], pitch: ['gs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [79.0], pitch: ['g5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		), // bar end
		12: ( // bar 12 start
			v1: [ // voice start
				(
					dur: 4.0,
					midinote: [74.0], pitch: ['d5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [66.0], pitch: ['fs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [73.0], pitch: ['cs5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [71.0], pitch: ['b4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [65.0], pitch: ['f4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [69.0], pitch: ['a4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [70.0], pitch: ['as4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [67.0], pitch: ['g4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [76.0], pitch: ['e5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [75.0], pitch: ['ds5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [68.0], pitch: ['gs4'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
				(
					dur: 4.0,
					midinote: [72.0], pitch: ['c5'],
					dynamic: \mp, velocity: 55,
					articulation: 'nil', tie: nil, slur: nil
				),
			] // voice end
		) // bar end
	) // part end
); // score end

~play = {
	s.waitForBoot {
		var parts, numBar, detectNumVoices, eventPlayer;
		parts = [ '' ];
		numBar = 12;
		detectNumVoices = { |nthBar, thisPart|
			~twelve_tone_series[thisPart][nthBar].keys.count { |item|
				item.asString.contains("v") }
		};
		eventPlayer = { |thisEntry, slur, instrument|
			var articuletionToVelocity, articuletionToLegato, tiedNoteVelocity, sustain;
			articuletionToVelocity = 0;
			case
			{ thisEntry[\articulation] == 'accent'          } { articuletionToVelocity = 4    }
			{ thisEntry[\articulation] == 'strong-accent'   } { articuletionToVelocity = 8    }
			{ thisEntry[\articulation] == 'staccato'        } { articuletionToLegato   = 0.5  }
			{ thisEntry[\articulation] == 'staccatissimo'   } { articuletionToLegato   = 0.25 }
			{ thisEntry[\articulation] == 'tenuto'          } { articuletionToLegato   = 1    }
			{ thisEntry[\articulation] == 'detached-legato' } { articuletionToLegato   = 0.7  }
			{ thisEntry[\articulation] == 'nil'             } {
				articuletionToLegato   = 1;
				articuletionToVelocity = 0
			};
			
			articuletionToLegato = if (slur == \on || (thisEntry[\tiedDur] != 0)) {1.01} {0.8};
			tiedNoteVelocity = if (thisEntry[\tie] == \stop) { 0 } { 1 };
			tiedNoteVelocity = if (thisEntry[\tie] == \stop) { 0 } { 1 };
			sustain = if (thisEntry['tiedDur'] != 0) {
				thisEntry['tiedDur']
			} {
				thisEntry['dur']
			};
			(
				instrument: instrument,
				dur:        if (thisEntry[\tiedDur] == 0) {
					thisEntry[\dur]
				} {
					thisEntry[\tiedDur]
				},
				amp:        thisEntry[\velocity] / 127 * tiedNoteVelocity,
				midinote:   thisEntry[\midinote],
				sustain:    sustain,
				legato:     if (thisEntry[\tiedDur] == 0) {
					thisEntry[\dur]
				} {
					thisEntry[\tiedDur]
				} * articuletionToLegato
			).play.postln;
			"".postln;
		};
		
		parts.do { |aPart|
			var nthBar, instrument, scorePlay;
			nthBar = 1;
			instrument = if (SynthDescLib.global.synthDescs.keys.includes(aPart)) {
				aPart
			} {
				\default
			};
			scorePlay = { |nthBarNum|
				var thisPartThisBarVoiceSize = detectNumVoices.(nthBarNum, aPart);
				("bar:" + nthBarNum).postln;
				thisPartThisBarVoiceSize.do { |thisVoiceIndex|
					fork{
						var thisPartThisBarThisVoice, thisPartThisBarThisVoiceItemSize, slur;
						thisPartThisBarThisVoice = ~twelve_tone_series
						[aPart][nthBarNum][
							("v" ++ (thisVoiceIndex + 1)).asSymbol
						];
						thisPartThisBarThisVoiceItemSize = thisPartThisBarThisVoice.size;
						thisPartThisBarThisVoiceItemSize.do { |index|
							var entry = thisPartThisBarThisVoice[index];
							("\n" ++ entry ++ "\n").postln;
							case
							{ entry.keys.includes(\tempo) } {
								TempoClock.default.tempo = entry[\tempo][\bpm] / 60;
								TempoClock.default.tempo.postln
							}
							{ thisPartThisBarThisVoice[index].keys.includes(\midinote) } {
								var tiedRhythmicValue = 0, waitTime;
								switch (entry[\slur],
									\start, { slur = \on },
									\stop, { slur = \off }
								);
								if (entry[\tie] == \start) {
									var actualiseRhythmicValue;
									actualiseRhythmicValue = { |testBar, itemIdx, testItem|
										var nextTestItem, nexttestItemIdx;
										tiedRhythmicValue = tiedRhythmicValue + testItem[\dur];
										if (itemIdx < (thisPartThisBarThisVoiceItemSize - 1)) {
											if (testItem[\tie] != \stop) {
												nexttestItemIdx = itemIdx + 1;
												nextTestItem = thisPartThisBarThisVoice
												[nexttestItemIdx];
												nextTestItem.put(\tieDurCorrection, 0);
												actualiseRhythmicValue
												.(testBar, nexttestItemIdx, nextTestItem)
											}
										} {
											if (testItem[\tie] != \stop) {
												var testNextNthBar = testBar + 1;
												nexttestItemIdx = 0;
												nextTestItem = ~twelve_tone_series
												[aPart][testNextNthBar]
												[
													(\v ++ (thisVoiceIndex + 1)).asSymbol
												][0];
												nextTestItem.put(\tieDurCorrection, 0);
												actualiseRhythmicValue
												.(testNextNthBar, nexttestItemIdx, nextTestItem)
											}
										}
									};
									actualiseRhythmicValue.(nthBarNum, index, entry);
								};
								entry.put(\tiedDur, tiedRhythmicValue);
								(
									"entry['tiedDur']:" + entry['tiedDur'] ++ ";" +
									"entry['dur']:" + entry['dur'] ++ ";" +
									"entry['tieDurCorrection']:" + entry['tieDurCorrection']
								).postln;
								eventPlayer.(entry, slur, instrument);
								waitTime = if (entry[\tieDurCorrection] != nil) {
									entry[\tieDurCorrection]
								} {
									if (entry[\tiedDur] == 0) {
										entry[\dur]
									} {
										entry[\tiedDur]
									}
								};
								(
									"thisVoiceIndex:" 
									+ thisVoiceIndex + waitTime
								).postln;
 								waitTime.wait
 							};
							if (index == (thisPartThisBarThisVoice.size - 1)) {
								if (nthBar < numBar) {
									nthBar = nthBar + 1;
									scorePlay.(nthBar)
								}
							}
						}
					}
				}
			};
			scorePlay.(nthBar)
		}
	}
};
~play.()
)
